### PR TITLE
Import patches from ShipSoft

### PR DESCRIPTION
**Pull request by ThomasRuf**
We need to be able to also transport neutrinos.

### CODE REVIEW

**Comment by ihrivnac** [comment]
The patch as it it cannot be merged.
1) TG4SteppingAction.h: this would disconnect the function also for the other applications where it is used. You can change the default number of max steps with the UI command:
/mcTracking/maxNofSteps value
Did you try to use this?
2) TG4ExtDecayer: this development will require to add also an interactive command which will allow to select this option also from a macro.  The default should be also changed to "not skip" neutrinos. I will implement this addition and let you know when it is available in master for test.

**Comment by ThomasRuf** [comment]
Hi,
concerning 1, I agree this is not for production. It is a temporary measure, since otherwise geant4_vmc crashes with seqfault. I did not tested if this problem disappeared in a more recent version. I will wait for 2, and then test it.
thanks,
thomas

Von: ihrivnac [mailto:notifications@github.com]
Gesendet: Donnerstag, 28. September 2017 03:38
An: vmc-project/geant4_vmc <geant4_vmc@noreply.github.com>
Cc: Thomas Ruf <Thomas.Ruf@cern.ch>; Author <author@noreply.github.com>
Betreff: Re: [vmc-project/geant4_vmc] Import patches from ShipSoft (#3)


The patch as it it cannot be merged.

  1.  TG4SteppingAction.h: this would disconnect the function also for the other applications where it is used. You can change the default number of max steps with the UI command:
/mcTracking/maxNofSteps value
Did you try to use this?
  2.  TG4ExtDecayer: this development will require to add also an interactive command which will allow to select this option also from a macro. The default should be also changed to "not skip" neutrinos. I will implement this addition and let you know when it is available in master for test.

**Comment by ihrivnac** [comment]
Could you try to update to master (commit f106dc601c3) ?  The neutrinos should not be skipped. I believe that the problem with TG4SteppingAction is already fixed. Please, let me know if you still get the break.

**Comment by ThomasRuf** [comment]
Great! Indeed, no crash anymore due to TG4SteppingAction. For the neutrinos, need a bit more time to check, but from looking at the code, can’t see how it cannot work.

Thanks,

thomas

Von: ihrivnac [mailto:notifications@github.com]
Gesendet: Donnerstag, 28. September 2017 08:54
An: vmc-project/geant4_vmc <geant4_vmc@noreply.github.com>
Cc: Thomas Ruf <Thomas.Ruf@cern.ch>; Author <author@noreply.github.com>
Betreff: Re: [vmc-project/geant4_vmc] Import patches from ShipSoft (#3)


Could you try to update to master (commit f106dc6<https://github.com/vmc-project/geant4_vmc/commit/f106dc601c3d0cc976d17f723fa304a1806b65dc>) ? The neutrinos should not be skipped. I believe that the problem with TG4SteppingAction is already fixed. Please, let me know if you still get the break.

**Comment by ihrivnac** [comment]
Dear Thomas,
I believe that all features asked in this PR were addressed in v3.5 version. Could you, please, confirm, so that we can close this PR? Thank you

**Comment by ThomasRuf** [comment]
yes, confirm that you can close the PR. thanks Thomas

**Pull request closed without merging**
